### ISSUE TITLE
Symbols overwrite stop working

### ISSUE THREAD

**Issue by OCTO-MAZ** [hoai265/Language-Sketch-Plugin#10]
Hi there! I just downloaded your awesome plugin!
Seems great, however, the text on symbols are not added to the json file.
Even with the "o_".
Can you confirme something is broken ?

**Comment by vash88** [comment]
I can't get translations to work on symbol overrides.

Steps to reproduce:
1. Translation Tool > Generate language file.
2. Make edits to JSON file for testing. 
3. Select Layer or Artboard and use Translation Tool > Translate.
4. Nothing happens.

I can confirm it's working for regular Layers and Artboards using the same steps.

A fix for this would be excellent! Much appreciated @hoai265

**Comment by hoai265** [comment]
Excuse me sir, your macOs is Catalina?

**Comment by vash88** [comment]
That's right I'm on:

macOS Catalina v10.15.3
Sketch Version 63.1

**Comment by hoai265** [comment]
We found some issues on Catalina and we are updating the tool. We will be back with new version of the tool to close this github issue. Thanks for using my tool sir.

**Comment by hoai265** [comment]
[Translation.sketchplugin.zip](https://github.com/hoai265/Language-Sketch-Plugin/files/4207655/Translation.sketchplugin.zip)
Could you test this version and confirm your problem?

**Comment by vash88** [comment]
Just tested it and having the same issue. I've emailed you my Sketch file and screen recording for you to see.

**Comment by hoai265** [comment]
To support symbol. You have to do some steps :
 - Change your symbol instance name with prefix o_
 - Override symbol instance content
