### ISSUE TITLE
Translate Menu doesn't open dialog

### ISSUE THREAD

**Issue by jfearnside** [hoai265/Language-Sketch-Plugin#4]
Im using Sketch 44.1 and we can generate the JSON file but cannot import it back in. When I click on the Translate menu item nothing happens. As per the realm I am expecting a dialog to allow language selection to open but it doesn't appear. Are their any dependancies that I may be missing?

**Comment by jfearnside** [comment]
I just figured out why its exhibiting this behavior. If you edit the output JSON file in the default text editor on the mac (TextEdit) then it saves the files with only mac style Line Feeds whereas the original file is outputting the file with CRLFs. If you edit the JSON in an editor like Atom by Github then this works flawlessly.

**Comment by jfearnside** [comment]
Hmm - may also be to with it the file is UTF-8 with a Byte order mark.

**Comment by hoai265** [comment]
@jfearnside So your problem is about the text editor? Right now i cannot support for any Sketch version > 40.3 because my license is outdate.

**Comment by jfearnside** [comment]
Kind of - the default text editor on the Mac saves the files out in a format that causes your plugin to malfunction. It would be nice if it handled the file from text editor. I have a work around now so please do not worry about this!
