### ISSUE TITLE
JSON function not working anymore

### ISSUE THREAD

**Issue by alex52** [hoai265/Language-Sketch-Plugin#7]
Hi there! I just downloaded your awesome plugin!

Seems great, however, creating the JSON doesn't seem to be working anymore. It creates an empty JSON without my text from the layers.

Would it be possible to fix this?

**Comment by hoai265** [comment]
Hi alex,
Thanks for using my plugin. My license for Sketch was expired so I haven't
updated the plugin for a year. But I will check and update as soon as
possible.

Many thanks,
Hoai Nguyen

**Comment by rdewolff** [comment]
Any update on this?

**Comment by hoai265** [comment]
Hey guys,
I just test the plugin to day with latest Sketch and everything seem still good. Can you show me more about your issue? Thanks.

**Comment by mariannadavila** [comment]
Hi @hoai265 I'm having troubles with the plugin! I can start translating everything perfectly, but once I go back to the Sketch file to "Translate" it won't do anything but if I try to tap on "generate new language file" again, the pop-up asking if I'd like to replace current file appears.. Is there any way to link the two files back together again?? Hopefully there is!! I love your plugin it's extremely helpful.

**Comment by hoai265** [comment]
Can you give me some image to understand more about your problem?

2018-06-06 0:30 GMT+07:00 mariannadavila <notifications@github.com>:

**Comment by Pennylele** [comment]
Hi @hoai265, I have the same issue as @alex52, the exported JSON file is empty: see screenshot (http://prntscr.com/kx8jzx). My mac version is MacOS High Sierra. Thank you!

**Comment by hoai265** [comment]
Have you change your text layer name you want to generate with prefix o_ ??
