### ISSUE TITLE
Improve success message

### ISSUE THREAD

**Issue by lukasoppermann** [hoai265/Language-Sketch-Plugin#8]
Hey, 
this is a really neat plugin.

To improve the ux of the plugin you could use a toast (message at the bottom) instead of an alert that has to be closed with a click on "OK" for the success message.

Additionally it would be better to provide a meaningful content on the messages, e.g. "File successfully translated" or "New strings added to language file: en".

**Comment by hoai265** [comment]
Can you support me to do that 👌 ?
